export const bookConstants = {
    GET_ALL_BOOK_REQUEST:'GET_ALL_BOOK_REQUEST',
    GET_ALL_BOOK_SUCCESS:'GET_ALL_BOOK_SUCCESS',
    GET_ALL_BOOK_FAILURE:'GET_ALL_BOOK_FAILURE',

    GET_A_BOOK_REQUEST:'GET_A_BOOK_REQUEST',
    GET_A_BOOK_SUCCESS:'GET_A_BOOK_SUCCESS',
    GET_A_BOOK_FAILURE:'GET_A_BOOK_FAILURE',

    UPDATE_BOOK_REQUEST:'UPDATE_BOOK_REQUEST',
    UPDATE_BOOK_SUCCESS:'UPDATE_BOOK_SUCCESS',
    UPDATE_BOOK_FAILURE:'UPDATE_BOOK_FAILURE',

    DELETE_BOOK_REQUEST:'DELETE_BOOK_REQUEST',
    DELETE_BOOK_SUCCESS:'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILURE:'DELETE_BOOK_FAILURE',
    
    ADD_NEW_BOOK_REQUEST:'ADD_NEW_BOOK_REQUEST',
    ADD_NEW_BOOK_SUCCESS:'ADD_NEW_BOOK_SUCCESS',
    ADD_NEW_BOOK_FAILURE:'ADD_NEW_BOOK_FAILURE',

}


export const cartConstants = {
    ADD_ITEM:'ADD_ITEM',
    CHANGE_QTY:'CHANGE_QTY',
    // ADD_ITEM_REQUEST:'ADD_ITEM_REQUEST',
    // ADD_ITEM_SUCCESS:'ADD_ITEM_SUCCESS',
    // ADD_ITEM_FAILURE:'ADD_ITEM_FAILURE',

}